# testnet or mainnet
TestNet = true

# chain data directory
Data = "data"

# Logging switch
Logging = true

# P2P configuration
#Externale ip (default = "0.0.0.0")
ExternalIp = "0.0.0.0"

# Custom boot
Boot = ""

# P2P port (default = "33330")
P2PPort="33310"


# RPC configuration, (default = 33331)
RpcPort = "33331"
# RPC password
RpcPass = ""

# TLS switch
RpcTLS = false

# Roll back the node chain to a certain height, -1 means not roll back
FallBackTo = -1


# If it is a block generating node, it needs to be configured
# Json file address of the address private key
KeyFile = "command/wallet/keystore/xBx2VZpE5RdC7cVfMgPet7rtWcmvtfRu7vH.json"
# Password to decrypt the private key json file
KeyPass = "1"

