# testnet or mainnet
TestNet = true

# chain data directory
Data = "data"

# Logging switch
Logging = true

# P2P configuration
#Externale ip (default = "0.0.0.0")
ExternalIp = "0.0.0.0"

# Custom boot
Boot = ""

# P2P port (default = "33330")
P2PPort="18913"


# RPC configuration, (default = 33331)
RpcPort = "18912"
# RPC password
RpcPass = ""

# TLS switch
RpcTLS = false

# Roll back the node chain to a certain height, -1 means not roll back
RollBack = 0


# If it is a block generating node, it needs to be configured
# Json file address of the address private key
KeyFile = "../wallet/keystore/xCBV6JvhbpjBdbwDVvuA9C26iyVqY13TWeS.json"
# Password to decrypt the private key json file
KeyPass = "1"

